### ISSUE TITLE
Fakestream ain't working

### ISSUE THREAD

**Issue by pranny** [octoai/gem-octocore#22]
I am unable to get fakestream to work. Here are the steps to reproduce
- Update gem-octocore to HEAD. Install gem-octocore using the provided `bin/clean_build.sh`
- Update gem-octoMessageAdapters to HEAD and install it using provided `clean_build.sh
- Update apiconsumer to HEAD. Editing the file `consumer.rb` to require `octomessageadapters` gem.
- Update config repo. Made the following changes to enable kong be used

``` yaml
 kong:
-  enabled: false
+  enabled: true
```
- Update apihandler to HEAD
- Start kong, zkServer, cassandra, redis, apiconsumer, apihandler
- Start fakestream by `fakestream /path/to/config`

Error encountered

``` bash
$ fakestream ~/workspace/octo/current/config/
/Users/pranav/workspace/octo/current/config/
Loading from Config file: /Users/pranav/workspace/octo/current/config//config.yml
Loading from Config file: /Users/pranav/workspace/octo/current/config//kong_config.yml
I, [2016-09-07T11:09:48.380941 #14208]  INFO -- Octo: Octo booting up.
I, [2016-09-07T11:09:48.383699 #14208]  INFO -- Octo: I'm connected now.
I, [2016-09-07T11:09:48.386946 #14208]  INFO -- Octo: Setting callbacks.
{:username=>"Octo"}
/Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:202:in `post': undefined method `+' for nil:NilClass (NoMethodError)
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:75:in `app_init'
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:41:in `stream'
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:61:in `stream_forever'
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:235:in `_main'
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:248:in `main'
    from /Users/pranav/workspace/octo/current/gem-octocore/bin/fakestream:254:in `<top (required)>'
    from /Users/pranav/.rvm/gems/ruby-2.1.5/bin/fakestream:23:in `load'
    from /Users/pranav/.rvm/gems/ruby-2.1.5/bin/fakestream:23:in `<main>'
    from /Users/pranav/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/pranav/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

The cause of the error is that in [L202](https://github.com/octoai/gem-octocore/blob/master/bin/fakestream#L202) of fakestream, it is using something called `base_url`  which is defined as a method in [L33](https://github.com/octoai/gem-octocore/blob/master/bin/fakestream#L33). This means that the config should have defined the `base_url` somewhere. But it is not available at the config repo in the files [config.yml](https://github.com/octoai/config/blob/local/config.yml) or [kong_config.yml](https://github.com/octoai/config/blob/local/kong_config.yml).

Is something I am missing? Are there any untested changes?

**Comment by dipankar** [comment]
@ravingupta has been assigned the same and will resolve this.

**Comment by ravingupta** [comment]
changes commited and merged in config repository

**Comment by dipankar** [comment]
@pranny Have a look and update/close.

**Comment by pranny** [comment]
looks great!
